// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnwpK2os7Qn0bsry67ZLH34kEJ-DsWQu4',
    appId: '1:794813148688:web:622437f06a3a672deea495',
    messagingSenderId: '794813148688',
    projectId: 'shopping-app-9f5c9',
    authDomain: 'shopping-app-9f5c9.firebaseapp.com',
    storageBucket: 'shopping-app-9f5c9.appspot.com',
    measurementId: 'G-JK36TEP6C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCczWqZm0oDmPuphm9WbTLOfhou7lgWmR4',
    appId: '1:794813148688:android:c13f981b83cd7850eea495',
    messagingSenderId: '794813148688',
    projectId: 'shopping-app-9f5c9',
    storageBucket: 'shopping-app-9f5c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv8KxmWZM9aXLgSzWecciSG5Rh-HLIwMk',
    appId: '1:794813148688:ios:758775d7eb7d06beeea495',
    messagingSenderId: '794813148688',
    projectId: 'shopping-app-9f5c9',
    storageBucket: 'shopping-app-9f5c9.appspot.com',
    iosBundleId: 'com.example.shopAdmin',
  );
}
